// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyButL7xChBAEJE2lQjty4TC8Tt9FH-vd18',
    appId: '1:303050505618:web:58e12e938e437674a6954b',
    messagingSenderId: '303050505618',
    projectId: 'cryptominer-24db5',
    authDomain: 'cryptominer-24db5.firebaseapp.com',
    storageBucket: 'cryptominer-24db5.firebasestorage.app',
    measurementId: 'G-RKEGLEB6EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4IFSutM1d0GtZ3P60AuM153QxG6ZYLco',
    appId: '1:303050505618:android:a16ba25663f80356a6954b',
    messagingSenderId: '303050505618',
    projectId: 'cryptominer-24db5',
    storageBucket: 'cryptominer-24db5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVCFCbbmHi1s4deINmWvg4aoeIC-TGA9w',
    appId: '1:303050505618:ios:525c5b4d1110cbaca6954b',
    messagingSenderId: '303050505618',
    projectId: 'cryptominer-24db5',
    storageBucket: 'cryptominer-24db5.firebasestorage.app',
    iosBundleId: 'com.app.projectminer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVCFCbbmHi1s4deINmWvg4aoeIC-TGA9w',
    appId: '1:303050505618:ios:525c5b4d1110cbaca6954b',
    messagingSenderId: '303050505618',
    projectId: 'cryptominer-24db5',
    storageBucket: 'cryptominer-24db5.firebasestorage.app',
    iosBundleId: 'com.app.projectminer1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyButL7xChBAEJE2lQjty4TC8Tt9FH-vd18',
    appId: '1:303050505618:web:73cdb4c580e0c2dca6954b',
    messagingSenderId: '303050505618',
    projectId: 'cryptominer-24db5',
    authDomain: 'cryptominer-24db5.firebaseapp.com',
    storageBucket: 'cryptominer-24db5.firebasestorage.app',
    measurementId: 'G-CZZV2YDXRC',
  );
}
